{% set name = "unicorn-binance-local-depth-cache" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 630d1c6f0a7d692e4aec3337061a3e7134435edd2c392387ce2908f179dce616

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - requests
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api >=1.40.5
  run:
    - python >=3.7
    - requests
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api >=1.40.5

test:
  imports:
    - unicorn_binance_local_depth_cache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-local-depth-cache.html
  summary: A local Binance DepthCache Manager for Python.
  description: |
    The Python package UNICORN Binance Local Depth Cache provides a local
    depth_cache for the Binance Exchanges Binance (+Testnet), Binance Futures
    (+Testnet).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-local-depth-cache
  doc_url: https://unicorn-binance-local-depth-cache.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner
