{% set name = "unicorn-binance-local-depth-cache" %}
{% set version = "2.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicorn_binance_local_depth_cache-{{ version }}.tar.gz
  sha256: a6ba7b55773bcb61ccdcbe252c94bf9fb2fc6434d530bf23d078348dba0dee71

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - mypy
  run:
    - python
    - aiohttp
    - cython >=3.0.10
    - orjson
    - requests >=2.32.3
    - unicorn-binance-websocket-api >=2.12.0
    - unicorn-binance-rest-api >=2.10.0

test:
  imports:
    - unicorn_binance_local_depth_cache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oliver-zehentleitner/unicorn-binance-local-depth-cache
  summary: A local Binance DepthCache Manager for Python.
  description: |
    A local Binance DepthCache manager for Python that supports multiple depth
    caches in one instance in an easy, fast, flexible, robust and fully-featured
    way. Part of the UNICORN Binance Suite.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/oliver-zehentleitner/unicorn-binance-local-depth-cache
  doc_url: https://oliver-zehentleitner.github.io/unicorn-binance-local-depth-cache

extra:
  recipe-maintainers:
    - oliver-zehentleitner
